### ISSUE TITLE
govc : Can't use # in password 

### ISSUE THREAD

**Issue by kikitux** [vmware/govmomi#273]
By default, vcsa requires one special character, so I use #

however, this cause the govc to fail to login:

. govc.env
./govc about
Error: Post https://administrator:Pass123/sdk#@192.168.1.28: dial tcp: unknown port tcp/Pass123

the password here is Pass123

export GOVC_URL="kikitux.net\administrator:Password123#@192.168.1.28"
export GOVC_INSECURE=1

**Comment by albers** [comment]
I have the same issue with [docker-machine](https://github.com/docker/machine) using its [vmwarevsphere driver](https://github.com/docker/machine/blob/master/docs/index.md#vmware-vsphere). The driver uses govc.

```
$ govc version
govc v0.1.0-52-g871f5d4

$ docker-machine --version
docker-machine version 0.3.0 (0a251fe)
```

**Comment by pietern** [comment]
I published a new release with the bits that fix this issue: [prerelease-v0.1.0-62-g7734772](https://github.com/vmware/govmomi/releases/tag/prerelease-v0.1.0-62-g7734772)

@albers Can you try not setting the user/pass in GOVC_URL and instead setting them in GOVC_USERNAME and GOVC_PASSWORD? Since the environment variables will be inherited by govc, this could also fix the issue when using docker machine (though this is an untested hypothesis).

**Comment by albers** [comment]
@pietern I cannot use environment variables here. `docker-machine` takes care of the credentials via its `--vmwarevsphere-username` and `--vmwarevsphere-password` options. Those are required, omitting them yields the following errors:

    Error creating machine: Incomplete vSphere information: missing vSphere username
    Error creating machine: Incomplete vSphere information: missing vSphere password

Setting the environment variables additionally did not change the behaviour.

**Comment by albers** [comment]
For my usecase, prerelease-v0.1.0-62-g7734772 does not resolve the issue. `docker-machine` might be the culprit though. I'ts not very mature.

Here's a session transscript:
```
$ docker-machine create --driver vmwarevsphere --vmwarevsphere-vcenter 10.10.10.10 --vmwarevsphere-username user --vmwarevsphere-password abc#123 --vmwarevsphere-network some-network --vmwarevsphere-datastore some-datastore --vmwarevsphere-datacenter some-datacenter test5
Generating SSH Keypair...
Uploading Boot2docker ISO ...
Creating directory test5 on datastore some-datastore of vCenter 10.10.10.10...
Error creating machine: Unable to mkdir on datastore some-datastore due to Error: Post https://user:abc/sdk#123@10.10.10.10: dial tcp: unknown port tcp/abc

You will want to check the provider to make sure the machine and associated resources were properly removed.
```

My usecase is not urgent. I already changed the vSphere password so that I could go on evaluating `docker-machine` and got stuck later anyway due to issues with it.

**Comment by albers** [comment]
Looks like govc uses some URL abstraction that recognizes the # as the beginning of a target and inserts the path in front of it. And it recoginzes the `:` in the inline authentication part as a port delimiter.

**Comment by pietern** [comment]
@albers Were you able to check with GOVC_USERNAME and GOVC_PASSWORD set when you tried out docker machine most recently? They take precedence over what is set via the URL, which means you can specify bogus values there to keep docker machine quiet, while govc will pick up the real values from the environment.

The URL parsing is done by Go's standard library and implements full URL parsing. Everything after the # is the URL fragment and tries to pull out a host and port from everything before that. That's why the : is interpreted as the port delimited. Specifying the URL alone was good enough for a while, but it doesn't help us in the case of special characters.

Thanks @kikitux and @albers for your help here.

**Comment by kikitux** [comment]
I can confirm that with the current release I can use GOVC_USER, GOVC_PASSWORD and GOVC_URL and works.

If I try to use only GOVC_URL it still hit the same issue, so I think should be a good idea put this in the govc readme??

 govc about                                                                                          
Error: Post https://kikitux.net\administrator:Password3643/sdk#@192.168.1.28: dial tcp: unknown port tcp/Password3643     

Variables were:
env | grep GOVC                                                                                     
GOVC_INSECURE=1                                                                                                                               
GOVC_URL=kikitux.net\administrator:Password3643#@192.168.1.28

**Comment by kikitux** [comment]
@pietern

**Comment by kikitux** [comment]
Please review this PR for the README of govc

https://github.com/vmware/govmomi/pull/279

Thanks very much

**Comment by albers** [comment]
@pietern This indeed helped. If I specify the problematic credentials in the environment and use dummy values in the `docker-machine` command, the invocation succeeds:
```
$ export GOVC_USERNAME=real_user
$ export GOVC_PASSWORD=real_password_with_hash
$ docker-machine create --driver vmwarevsphere --vmwarevsphere-vcenter 10.10.10.10 --vmwarevsphere-username dummy --vmwarevsphere-password dummy --vmwarevsphere-network some-network --vmwarevsphere-datastore some-datastore --vmwarevsphere-datacenter some-datacenter test
```
Thanks, Pieter. With this workaround I can continue evaluating `docker-machine`.

**Comment by pietern** [comment]
@albers Great!

**Comment by kikitux** [comment]
all, I wanted to do an update, that for some reason I just forgot this..

if `#` and `:` have a different meaning in the url, they should be escaped on the variable, and that's is..

I have tested and works.. not sure why this slipped from my radar when I did hit this issue.

So, I just change my:

`domain\administrator:Password123#@192.168.1.28`

into

`domain\administrator:Password123%23@192.168.1.28`

sample:
```
alvaros-Mac-mini:vagrant_vsphere alvarom$ . govc.env ; govc about
Name:         VMware vCenter Server
Vendor:       VMware, Inc.
Version:      6.0.0
Build:        2656761
OS type:      linux-x64
API type:     VirtualCenter
API version:  6.0
Product ID:   vpx
UUID:         c9f0242f-10e3-4e10-85d7-5eea7c855188
alvaros-Mac-mini:vagrant_vsphere alvarom$ echo $GOVC_URL
domain\administrator:Password123%23@192.168.1.28
alvaros-Mac-mini:vagrant_vsphere alvarom$ 
```

Documenting here in case someone find this in the future.


`#` = `%23`
`:` = `%3A`

Full list here:
http://www.w3schools.com/tags/ref_urlencode.asp

**Comment by kikitux** [comment]
@albers 

If you have the time, can you test escape the # in your password and replace it with `%23` ?

**Comment by albers** [comment]
@kikitux URL escaping the `#` in the password works for me.
With this trick, I can directly specify the credentials in docker-machine:
```
$ docker-machine create --driver vmwarevsphere --vmwarevsphere-vcenter 10.10.10.10 --vmwarevsphere-username username --vmwarevsphere-password password_with_quoted_hash --vmwarevsphere-network some-network --vmwarevsphere-datastore some-datastore --vmwarevsphere-datacenter some-datacenter test
```
@pietern Shouldn't quoting be moved to govc so that it isn't the responsibility of the user?

**Comment by pietern** [comment]
@albers What do you mean by that? govc isn't able to tell quoted credentials apart from non-quoted credentials. If the user wants to specify the username/password verbatim, the only solution is to use separate variables such that escaping special characters is not necessary.

Regarding docker machine, this PR by @frapposelli should make this a non-issue: https://github.com/docker/machine/pull/1522

**Comment by albers** [comment]
But govc knows whether the credentials were supplied via the environment, in which case quoting should be avoided. In case of URL inline authentication, automatic quoting would be very helpful as the user won't be able to get his verbatim password through anyway. URL encoding is not very common as a quoting method, so the user might be confused.

Thanks for pointing me to the docker-machine PR, that's good news.

**Comment by pietern** [comment]
For the same reason that govc can't parse a password with special characters out of an URL, we can't do automatic escaping either. If you use `pass@host:1234` as password, it can't tell whether the `host` is the host or part of the password, or if `1234` is the port or part of the password. So if you want to specify your username and password without worrying about escaping at all, the only way is to use a separate variable to specify them, where there is no need to interpret whatever is specified.
